name: Test setup-dune Action

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, macos-13]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use local setup-dune action
        uses: ./
        with:
          automagic: false
      - name: Show dune version
        run: dune --version
